/**
 * @author RubioAlves
 * Created 24/04/2022 at 08:38
 */
object Dependencies {
    const val core_gradle_plugin="com.corelibrary.gradle:build-configuration:${Version.core_gradle_plugin_version}"
    const val gradle="com.android.tools.build:gradle:${Version.gradle_version}"
    const val kotlin_gradle="org.jetbrains.kotlin:kotlin-gradle-plugin:${Version.kotlin_plugin_version}"
    const val kotlin = "org.jetbrains.kotlin:kotlin-stdlib:${Version.kotlin_version}"
    const val kotlin_jdk = "org.jetbrains.kotlin:kotlin-stdlib-jdk8:${Version.kotlin_version}"
    const val core_ktx="androidx.core:core-ktx:${Version.core_ktx_version}"
    const val appcompat="androidx.appcompat:appcompat:${Version.appcompat_version}"
    const val material="com.google.android.material:material:${Version.material_version}"
    const val view_binding="androidx.databinding:viewbinding:${Version.view_binding_version}"
    const val constraint_layout="androidx.constraintlayout:constraintlayout:${Version.constraint_layout_version}"

    const val compose_ui="androidx.compose.ui:ui:${Version.compose_version}"
    const val compose_tooling="androidx.compose.ui:ui-tooling:${Version.compose_version}"
    const val compose_foundation="androidx.compose.foundation:foundation:${Version.compose_version}"
    const val compose_material="androidx.compose.material:material:${Version.compose_version}"
    const val compose_material_icons_core="androidx.compose.material:material-icons-core:${Version.compose_version}"
    const val compose_material_icons_extended="androidx.compose.material:material-icons-extended:${Version.compose_version}"
    const val compose_livedata="androidx.compose.runtime:runtime-livedata:${Version.compose_version}"
    const val compose_ui_test="androidx.compose.ui:ui-test-junit4:${Version.compose_version}"

    const val navigation_fragment="androidx.navigation:navigation-fragment-ktx:${Version.navigation_version}"
    const val navigation_ui="androidx.navigation:navigation-ui-ktx:${Version.navigation_version}"
    const val lifecycle_livedata="androidx.lifecycle:lifecycle-livedata-ktx:${Version.lifecycle_version}"
    const val lifecycle_viewmodel="androidx.lifecycle:lifecycle-viewmodel-ktx:${Version.lifecycle_version}"
    const val lifecycle_runtime="androidx.lifecycle:lifecycle-runtime-ktx:${Version.lifecycle_version}"
    const val facebook_shimmer="com.facebook.shimmer:shimmer:${Version.facebook_shimmer_version}"
    const val retrofit="com.squareup.retrofit2:retrofit:${Version.retrofit_version}"
    const val converter_gson="com.squareup.retrofit2:converter-gson:${Version.retrofit_version}"
    const val okhttp3_logging_interceptor= "com.squareup.okhttp3:logging-interceptor:${Version.okhttp3_logging_interceptor_version}"
    const val glide_compiler="com.github.bumptech.glide:compiler:${Version.glide_version}"
    const val glide="com.github.bumptech.glide:glide:${Version.glide_version}"
    const val koin= "io.insert-koin:koin-android:${Version.koin_version}"
    const val mockk="io.mockk:mockk:${Version.mockk_version}"
    const val mockk_android="io.mockk:mockk-android:${Version.mockk_version}"
    const val room_runtime="androidx.room:room-runtime:${Version.room_version}"
    const val room="androidx.room:room-compiler:${Version.room_version}"
    const val room_kts="androidx.room:room-ktx:${Version.room_version}"
    const val room_testing="androidx.room:room-testing:${Version.room_version}"
    const val koin_test="io.insert-koin:koin-test:${Version.koin_version}"
    const val junit="junit:junit:${Version.junit_version}"
    const val ext_junit="androidx.test.ext:junit:${Version.ext_junit_version}"
    const val espresso_core="androidx.test.espresso:espresso-core:${Version.espresso_core_version}"
}